
# [CVE-2019-10761](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-10761)

## Description

- `This affects the package vm2 before 3.6.11. It is possible to trigger a RangeError exception from the host rather than the "sandboxed" context by reaching the stack call limit with an infinite recursion. The returned object is then used to reference the mainModule property of the host code running the script allowing it to spawn a child_process and execute arbitrary code.`

## Cvss Data

- **Access Vector**:
  - 
- **Base Score**:
  - 

## Scores

- **Exploitability Score**:
  - 
- **Impact Score**:
  - 
- **Base Severity**:
  - 

## Other Information

- **Publish Date**:
  - 2022-07-13 09:15:08
- **Vulnerability Status**:
  - Analyzed

## References

- **report@snyk.io**: https://github.com/patriksimek/vm2/commit/4b22d704e4794af63a5a2d633385fd20948f6f90
- **report@snyk.io**: https://github.com/patriksimek/vm2/issues/197
- **report@snyk.io**: https://snyk.io/vuln/SNYK-JS-VM2-473188
