
# [CVE-2009-5011](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-5011)

## Description

- `Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 4.3

## Scores

- **Exploitability Score**:
  - 8.6
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2010-10-19 20:00:03
- **Vulnerability Status**:
  - Analyzed

## References

- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/issues/detail?id=100
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/source/detail?r=543
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/source/diff?spec=svn543&r=543&format=side&path=/trunk/pyftpdlib/ftpserver.py
