
# [CVE-2020-24584](https://docs.djangoproject.com/en/dev/releases/security/)

## Description

- `An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 5.0

## Scores

- **Exploitability Score**:
  - 10.0
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2020-09-01 13:15:11
- **Vulnerability Status**:
  - Modified

## References

- **cve@mitre.org**: https://docs.djangoproject.com/en/dev/releases/security/
- **cve@mitre.org**: https://groups.google.com/forum/#%21topic/django-announce/Gdqn58RqIDM
- **cve@mitre.org**: https://groups.google.com/forum/#%21topic/django-announce/zFCMdgUnutU
- **cve@mitre.org**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/F2ZHO3GZCJMP3DDTXCNVFV6ED3W64NAU/
- **cve@mitre.org**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/OLGFFLMF3X6USMJD7V5F5P4K2WVUTO3T/
- **cve@mitre.org**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZCRPQCBTV3RZHKVZ6K6QOAANPRZQD3GI/
- **cve@mitre.org**: https://security.netapp.com/advisory/ntap-20200918-0004/
- **cve@mitre.org**: https://usn.ubuntu.com/4479-1/
- **cve@mitre.org**: https://www.djangoproject.com/weblog/2020/sep/01/security-releases/
- **cve@mitre.org**: https://www.openwall.com/lists/oss-security/2020/09/01/2
- **cve@mitre.org**: https://www.oracle.com/security-alerts/cpujan2021.html
