
# [CVE-2022-42731](https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58)

## Description

- `mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage.`

## Cvss Data

- **Access Vector**:
  - 
- **Base Score**:
  - 

## Scores

- **Exploitability Score**:
  - 
- **Impact Score**:
  - 
- **Base Severity**:
  - 

## Other Information

- **Publish Date**:
  - 2022-10-11 14:15:10
- **Vulnerability Status**:
  - Analyzed

## References

- **cve@mitre.org**: https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58
- **cve@mitre.org**: https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release
- **cve@mitre.org**: https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release
