
# [CVE-2010-3494](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-3494)

## Description

- `Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 4.3

## Scores

- **Exploitability Score**:
  - 8.6
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2010-10-19 20:00:04
- **Vulnerability Status**:
  - Analyzed

## References

- **cve@mitre.org**: http://bugs.python.org/issue6706
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/issues/detail?id=104
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/issues/detail?id=105
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/source/detail?r=556
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/source/diff?spec=svn556&r=556&format=side&path=/trunk/pyftpdlib/ftpserver.py
- **cve@mitre.org**: http://www.openwall.com/lists/oss-security/2010/09/09/6
- **cve@mitre.org**: http://www.openwall.com/lists/oss-security/2010/09/11/2
- **cve@mitre.org**: http://www.openwall.com/lists/oss-security/2010/09/22/3
- **cve@mitre.org**: http://www.openwall.com/lists/oss-security/2010/09/24/3
- **cve@mitre.org**: https://bugs.launchpad.net/zodb/+bug/135108
