
# [CVE-2021-29556](https://github.com/tensorflow/tensorflow/commit/4071d8e2f6c45c1955a811fee757ca2adbe462c1)

## Description

- `TensorFlow is an end-to-end open source platform for machine learning. An attacker can cause a denial of service via a FPE runtime error in `tf.raw_ops.Reverse`. This is because the implementation(https://github.com/tensorflow/tensorflow/blob/36229ea9e9451dac14a8b1f4711c435a1d84a594/tensorflow/core/kernels/reverse_op.cc#L75-L76) performs a division based on the first dimension of the tensor argument. The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.`

## Cvss Data

- **Access Vector**:
  - LOCAL
- **Base Score**:
  - 2.1

## Scores

- **Exploitability Score**:
  - 3.9
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - LOW

## Other Information

- **Publish Date**:
  - 2021-05-14 20:15:13
- **Vulnerability Status**:
  - Analyzed

## References

- **security-advisories@github.com**: https://github.com/tensorflow/tensorflow/commit/4071d8e2f6c45c1955a811fee757ca2adbe462c1
- **security-advisories@github.com**: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-fxqh-cfjm-fp93
