
# [CVE-2013-4260](http://www.ansible.com/security)

## Description

- `lib/ansible/playbook/__init__.py in Ansible 1.2.x before 1.2.3, when playbook does not run due to an error, allows local users to overwrite arbitrary files via a symlink attack on a retry file with a predictable name in /var/tmp/ansible/.`

## Cvss Data

- **Access Vector**:
  - LOCAL
- **Base Score**:
  - 3.3

## Scores

- **Exploitability Score**:
  - 3.4
- **Impact Score**:
  - 4.9
- **Base Severity**:
  - LOW

## Other Information

- **Publish Date**:
  - 2013-09-16 19:14:39
- **Vulnerability Status**:
  - Modified

## References

- **secalert@redhat.com**: http://www.ansible.com/security
- **secalert@redhat.com**: https://bugzilla.redhat.com/show_bug.cgi?id=998227
- **secalert@redhat.com**: https://exchange.xforce.ibmcloud.com/vulnerabilities/86898
- **secalert@redhat.com**: https://groups.google.com/forum/#%21topic/ansible-project/UVDYW0HGcNg
